#!/bin/sh

# lssrvrs

aws ec2 describe-instances \
  --query "Reservations[].Instances[]
           [State.Name,InstanceType,InstanceId,
           Placement.AvailabilityZone,VpcId,
           PublicIpAddress,SubnetId]" \
  --output text

