#!/bin/sh

# mksecgroup <secgroupname> <vpcId>

secgroupname=$1
vpcId=$2


groupId=$(aws ec2 create-security-group \
          --group-name $secgroupname \
          --description "$secgroupname" \
          --vpc-id $vpcId --query 'GroupId' \
          --output text)

aws ec2 authorize-security-group-ingress \
    --group-id $groupId \
    --protocol tcp --port 22 \
    --cidr 0.0.0.0/0

printf 'done'
